apiVersion: v1
kind: LimitRange
metadata:
  name: mini-book-hub-default-limits
  namespace: mini-book-hub-local
  labels:
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
    environment: local
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 512Mi
