apiVersion: v1
kind: ResourceQuota
metadata:
  name: mini-book-hub-local-quota
  namespace: mini-book-hub-local
  labels:
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
    environment: local
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "20"
    services: "10"
    configmaps: "20"
