apiVersion: v1
kind: ConfigMap
metadata:
  name: reader-service-config
  labels:
    app.kubernetes.io/name: reader-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
data:
  NODE_ENV: "production"
  SERVICE_NAME: "reader-service"
