apiVersion: v1
kind: Service
metadata:
  name: reader-service
  labels:
    app.kubernetes.io/name: reader-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reader-service
  ports:
    - name: http
      port: 3000
      targetPort: http
