labels:
  - pairs:
      environment: preview
      preview.mini-book-hub.io/profile: reader-service
    includeSelectors: false

resources:
  - ../../reader-service/base

patches:
  - target:
      kind: Rollout
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
