apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: book-service
  labels:
    app.kubernetes.io/name: book-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: book-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
