apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenthanhdat2707/XBrain_Phase2_Gitops.git
    targetRevision: main
    path: apps/mini-book-hub/frontend/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: mini-book-hub-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - SkipDryRunOnMissingResource=true
