apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.2.3
    helm:
      releaseName: monitoring
      values: |
        alertmanager:
          enabled: false

        grafana:
          enabled: false

        prometheus:
          prometheusSpec:
            podMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            ruleNamespaceSelector: {}
            ruleSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false

        prometheusOperator:
          admissionWebhooks:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
