apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenthanhdat2707/XBrain_Phase2_Gitops.git
    targetRevision: HEAD
    path: platform/preview-plugin/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
