apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mini-book-hub
    app.kubernetes.io/managed-by: argocd
data:
  NODE_ENV: "production"
  SERVICE_NAME: "order-service"
  BOOK_SERVICE_URL: "http://book-service:3000"
  READER_SERVICE_URL: "http://reader-service:3000"
